"""Add work types and compatibility rules

Revision ID: 29bcb585ea39
Revises: 72782017c10f
Create Date: 2026-09-07 00:30:05.250836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29bcb585ea39'
down_revision: Union[str, Sequence[str], None] = '72782017c10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('requires_traffic_block', sa.Boolean(), nullable=False),
    sa.Column('requires_power_block', sa.Boolean(), nullable=False),
    sa.Column('requires_ohe_isolation', sa.Boolean(), nullable=False),
    sa.Column('requires_signal_disconnection', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('work_compatibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type_a_id', sa.Integer(), nullable=False),
    sa.Column('work_type_b_id', sa.Integer(), nullable=False),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['work_type_a_id'], ['work_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_b_id'], ['work_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type_a_id', 'work_type_b_id', name='uq_work_type_pairs')
    )
    # Kept PostGIS tables untouched
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'work_types', ['work_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('work_type_id')

    # Kept PostGIS tables untouched

    op.drop_table('work_compatibility_rules')
    op.drop_table('work_types')
    # ### end Alembic commands ###
