"""Add requested_date to MaintenanceRequest

Revision ID: 49bcc5b4ea4d
Revises: 29bcb585ea39
Create Date: 2026-09-07 18:41:18.216468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49bcc5b4ea4d'
down_revision: Union[str, Sequence[str], None] = '29bcb585ea39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_date', sa.Date(), nullable=False, server_default='2026-09-07'))
        batch_op.alter_column('requested_date', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_column('requested_date')

    pass

    # ### end Alembic commands ###
