"""Add work types and compatibility rules

Revision ID: 7b2729d9cd19
Revises: acb9976f46c9
Create Date: 2026-09-05 16:34:21.019911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2729d9cd19'
down_revision: Union[str, Sequence[str], None] = 'acb9976f46c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_maintenance_requests_work_type_id', 'work_types', ['work_type_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
