"""Initial schema

Revision ID: acb9976f46c9
Revises: 
Create Date: 2026-09-05 15:39:31.274377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb9976f46c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='ck_department_name_nonempty'),
    sa.CheckConstraint('length(short_code) > 0', name='ck_department_short_code_nonempty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('schedule_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('total_windows', sa.Integer(), nullable=False),
    sa.Column('co_located_windows', sa.Integer(), nullable=False),
    sa.Column('unscheduled_count', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solve_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('manual', 'optimized')", name='ck_run_mode_valid'),
    sa.CheckConstraint('co_located_windows >= 0', name='ck_run_coloc_nonneg'),
    sa.CheckConstraint('solve_time_ms >= 0', name='ck_run_solve_time_nonneg'),
    sa.CheckConstraint('total_hours >= 0', name='ck_run_total_hours_nonneg'),
    sa.CheckConstraint('total_windows >= 0', name='ck_run_total_windows_nonneg'),
    sa.CheckConstraint('unscheduled_count >= 0', name='ck_run_unsched_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_week_mode', 'schedule_runs', ['week_start_date', 'mode'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('window_start_hour', sa.Integer(), nullable=False, comment='Minutes from midnight for nightly window start (e.g. 60 = 01:00)'),
    sa.Column('window_duration_hours', sa.Integer(), nullable=False, comment='Window duration in minutes (e.g. 180 = 3 hours)'),
    sa.Column('mega_day', sa.String(length=10), nullable=True),
    sa.Column('mega_duration_hours', sa.Integer(), nullable=True, comment='Mega block duration in minutes'),
    sa.Column('slot_capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(code) > 0', name='ck_section_code_nonempty'),
    sa.CheckConstraint('length(name) > 0', name='ck_section_name_nonempty'),
    sa.CheckConstraint('mega_duration_hours IS NULL OR mega_duration_hours > 0', name='ck_section_mega_duration_positive'),
    sa.CheckConstraint('slot_capacity > 0', name='ck_section_slot_capacity_positive'),
    sa.CheckConstraint('window_duration_hours > 0 AND window_duration_hours <= 1440', name='ck_section_window_duration_range'),
    sa.CheckConstraint('window_start_hour >= 0 AND window_start_hour < 1440', name='ck_section_window_start_hour_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_section_code', 'sections', ['code'], unique=False)
    op.create_table('block_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False, comment='Minutes from midnight (0-1439). E.g. 60 = 01:00, 90 = 01:30'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Window duration in minutes'),
    sa.Column('slot_capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint("day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')", name='ck_bw_day_of_week_valid'),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 1440', name='ck_bw_duration_range'),
    sa.CheckConstraint('slot_capacity > 0', name='ck_bw_slot_capacity_positive'),
    sa.CheckConstraint('start_minute >= 0 AND start_minute < 1440', name='ck_bw_start_minute_range'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'week_start_date', 'day_of_week', 'start_minute', name='uq_bw_section_week_day_start')
    )
    op.create_index('ix_bw_section_id', 'block_windows', ['section_id'], unique=False)
    op.create_index('ix_bw_week_start_date', 'block_windows', ['week_start_date'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('task_description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('critical', 'high', 'medium', 'low')", name='ck_request_severity_valid'),
    sa.CheckConstraint("status IN ('pending', 'scheduled', 'unscheduled')", name='ck_request_status_valid'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_request_duration_positive'),
    sa.CheckConstraint('length(task_description) > 0', name='ck_request_description_nonempty'),
    sa.CheckConstraint('overdue_days >= 0', name='ck_request_overdue_nonnegative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_department_id', 'maintenance_requests', ['department_id'], unique=False)
    op.create_index('ix_request_section_id', 'maintenance_requests', ['section_id'], unique=False)
    op.create_index('ix_request_severity', 'maintenance_requests', ['severity'], unique=False)
    op.create_index('ix_request_status', 'maintenance_requests', ['status'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('block_window_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.CheckConstraint("mode IN ('manual', 'optimized')", name='ck_assignment_mode_valid'),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'week_start_date', 'mode', name='uq_assignment_request_week_mode')
    )
    op.create_index('ix_assignment_block_window_id', 'schedule_assignments', ['block_window_id'], unique=False)
    op.create_index('ix_assignment_request_id', 'schedule_assignments', ['request_id'], unique=False)
    op.create_index('ix_assignment_week_mode', 'schedule_assignments', ['week_start_date', 'mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_week_mode', table_name='schedule_assignments')
    op.drop_index('ix_assignment_request_id', table_name='schedule_assignments')
    op.drop_index('ix_assignment_block_window_id', table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index('ix_request_status', table_name='maintenance_requests')
    op.drop_index('ix_request_severity', table_name='maintenance_requests')
    op.drop_index('ix_request_section_id', table_name='maintenance_requests')
    op.drop_index('ix_request_department_id', table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index('ix_bw_week_start_date', table_name='block_windows')
    op.drop_index('ix_bw_section_id', table_name='block_windows')
    op.drop_table('block_windows')
    op.drop_index('ix_section_code', table_name='sections')
    op.drop_table('sections')
    op.drop_index('ix_run_week_mode', table_name='schedule_runs')
    op.drop_table('schedule_runs')
    op.drop_table('departments')
    # ### end Alembic commands ###
